### ISSUE TITLE
Does it lack a dir ./public/assets/dist/ ?

### ISSUE THREAD

**Issue by eternaltao** [octoblu/email-password-site#1]
In the file of gulpfile.coffee:

```
gulp.src files
    .pipe plumber()
    .pipe coffee()
    .pipe concat('application.js')
    .pipe sourcemaps.write('.')
    .pipe gulp.dest('./public/assets/dist/')
```

It's need the dir named  /dist/  but  in ~/login.octoblu.com/public/assets/   there lacks the dist dir which includes application.js and so on.

**Comment by kmariano** [comment]
if you run gulp in the root directory of the project it will create this file. login.octoblu.com is deployed based on the build and is served from the correct folder.
